### ISSUE TITLE
Replace the "Eclipse Foundation Events" section by a "Purpose" section

### ISSUE THREAD

**Issue by Mogztter** [EclipseFdn/asciidoc-wg.eclipse.org#29]
I think we should replace (or at least move it lower on the page) the "Eclipse Foundation Events" as it can be a bit misleading.

Here's the current content:

![current](https://user-images.githubusercontent.com/333276/113488146-7c978780-94bc-11eb-89d0-9ca84024576b.png)

As you can see "Eclipse Foundation Events" section takes a lot of space and even draw the attention away from the hero section.

I think we should instead use this section to describe the purpose/mission of the Working Group.
Here's an example:
![purpose](https://user-images.githubusercontent.com/333276/113488197-d6984d00-94bc-11eb-9e2a-5e254f35438c.png)

https://science.eclipse.org/

**Comment by ahus1** [comment]
I agree, the current content is distracting. Other sites like iot.eclipse.org have iot news on them. As long as we don't have AsciiDoc news, putting purpose there and linking to the about page sounds like a good idea.

For the next milestone I wanted to review the "call to action" on each page. On the "About" page it is currently "please subscribe to the mailing list". I am all ears for other ideas.

**Comment by Mogztter** [comment]
OK I will open a pull request so we can compare before and after with Netlify preview 👍


> As long as we don't have AsciiDoc news, putting purpose there and linking to the about page sounds like a good idea.

No other working groups seem to be doing that but should we add/publish the next steering meeting as an event?
As far as I understand events and news are not static Markdown/AsciiDoc files but managed by another system? https://newsroom.eclipse.org/node/add/events ?

> For the next milestone I wanted to review the "call to action" on each page. On the "About" page it is currently "please subscribe to the mailing list". I am all ears for other ideas.

I will take a look and let you know if I get an idea.

**Comment by Mogztter** [comment]
Oh! this block is actually the default "featured story" and as far as I understand the content is fetched from: https://newsroom.eclipse.org/api/featured_story.
For instance: https://newsroom.eclipse.org/api/featured_story?parameters%5Bpublish_to%5D=science

@ahus1 Do you know how to post a featured story? On https://newsroom.eclipse.org/ I cannot only submit a news or an event.

**Comment by ahus1** [comment]
Sorry, don't have information about this. A quick search didn't reveal leads for me. 

@chrisguindon - could you please shed some light on how "featured stories" are supposed to work? Thanks!

**Comment by Mogztter** [comment]
I just found: https://eclipsefdn-hugo-solstice-theme.netlify.app/components/featured_story/

> You can add a featured story to a markdown file using the page parameter: show_featured_story: true
> To add featured stories, a new entry can be submitted via the [Newsroom](https://newsroom.eclipse.org/) site using the [Add Featured Story](https://newsroom.eclipse.org/node/add/featured-story) page if you have access. To update what content is retrieved from the featured content API, a parameter of featured_content_publish_target can be set in the page or site parameters. This parameter would apply to both the featured footer and featured story content and would be the publish target for the given site (e.g. eclipse_org, eclipse_iot, jakarta_ee).

Unfortunately, I get a "403 Access denied" on: https://newsroom.eclipse.org/node/add/featured-story

**Comment by autumnfound** [comment]
> Unfortunately, I get a "403 Access denied" on: https://newsroom.eclipse.org/node/add/featured-story

Yeah, you'll need a set of privileges to maintain those stories. We curate those currently to protect what sort of content can go in newsroom, so we can at least help you out there in getting some more useful content live. 

> Oh! this block is actually the default "featured story" and as far as I understand the content is fetched from: https://newsroom.eclipse.org/api/featured_story.
> For instance: https://newsroom.eclipse.org/api/featured_story?parameters%5Bpublish_to%5D=science

You're right that we have a default that we configure, this way we can always have some baseline of somewhat useful information to show there (like virtual events in our space). Displaying the featured story section at the top of the page is an opt-in component, so if you remove `show_featured_story: true` from the page parameters, that section would disappear.

> No other working groups seem to be doing that but should we add/publish the next steering meeting as an event?
> As far as I understand events and news are not static Markdown/AsciiDoc files but managed by another system? https://newsroom.eclipse.org/node/add/events ?

As for using events to do meetings, that's a no-go. The events for sites are part of the same set of data that drives our events.eclipse.org, so we are pretty careful about what gets added there. You are totally free to make a new set of data to show there in the same format though!

**Comment by autumnfound** [comment]
As an aside for additional info, in the `./content/_index.adoc` file, if you replace the following chunk, you can replace the events content section with your own stuff. If you make a shortcode under `./layouts/shortcodes`, you can use HTML as well! 

```
{{< newsroom/events
          title="Events"
          titleClass="heading-line text-center"
          containerClass="news-items event-container"
          id="events-list-container"
          publishTarget="asciidoc"
          count="5"
          templateId="event-list-format"
          templatePath="node_modules/eclipsefdn-hugo-solstice-theme/js/templates/event-list-format.mustache"
          includeList="true" >}}
```

**Comment by Mogztter** [comment]
Thanks @autumnfound for the valuable information 👍🏻 

Could you please take a look at what I did in https://github.com/EclipseFdn/asciidoc-wg.eclipse.org/pull/34?
I'm now using a custom layout on the index page to provide a static "featured story" block.
Not sure if it's the right way to do it... I quite like the block style so I'm using the exact same classes.

> As for using events to do meetings, that's a no-go. The events for sites are part of the same set of data that drives our events.eclipse.org, so we are pretty careful about what gets added there.

Got it.

> You are totally free to make a new set of data to show there in the same format though!

Interesting!

**Comment by chrisguindon** [comment]
> Unfortunately, I get a "403 Access denied" on: https://newsroom.eclipse.org/node/add/featured-story

The Eclipse Marketing team is responsible for updating the featured stories on the site. //cc @shanda-eclipse 

The featured story at the top of the homepage is optional, however, we would expect the site to keep our featured-story-footer on all pages.

**Comment by chrisguindon** [comment]
@shanda-eclipse What is the best way to request changes to the featured story of a site? Is it by email to news@eclipse.org?

**Comment by shanda-eclipse** [comment]
> @shanda-eclipse What is the best way to request changes to the featured story of a site? Is it by email to [news@eclipse.org](mailto:news@eclipse.org)?

Yes, please send content updated to news@eclipse.org. If you have the content ready, you can also drop it in this bug and I can update it now.

**Comment by ahus1** [comment]
I'll first merge @Mogztter's PR to replace the current featured story "Eclipse Foundation Events" with the "Purpose". This resolves this issue as the Eclipse Events are already linked on the start page (the "Events" -> "view all"), and having the content in the Git repo allows the project to maintain it without sending emails to get content change. 

I'll open a follow-up issue to explore what the intention of "featured content" together with the marketing team.
