### ISSUE TITLE
Rename repository to asciidoc-wg.eclipse.org

### ISSUE THREAD

**Issue by ahus1** [EclipseFdn/asciidoc-wg.eclipse.org#3]
The AsciiDoc Working Group will have two web sites:
* one to promote the language (asciidoc.org)
* one to introduce the working group and its members 

To make a better distinction of the two, the website of the working group steering committee decided that the working group website should be named **asciidoc-wg.eclipse.org**

@eclipsewebmaster  - could you please 
* rename this repository from `asciidoc.eclipse.org` to `asciidoc-wg.eclipse.org`
* rename the preview from `https://eclipsefdn-asciidoc.netlify.app/` to `https://eclipsefdn-asciidoc-wg.netlify.app/` (and change 

Thanks!

**Comment by ahus1** [comment]
@chrisguindon - can you or one of your colleagues please look into this to rename the repo? Thanks!

**Comment by ahus1** [comment]
@chrisguindon - the change #17 worked Netlify builds on the _main_ branch. Unfortunately it seems that branches no longer receive a preview build. Could you please have a look?

**Comment by ahus1** [comment]
Sorry, just seems to be a bit of delay at GitHub at the moment, here they come.

**Comment by chrisguindon** [comment]
No worries! I do notice some delays sometimes!
