### ISSUE TITLE
Design: extend the background image over the menu

### ISSUE THREAD

**Issue by Mogztter** [EclipseFdn/asciidoc-wg.eclipse.org#30]
A few Working Groups are using this design and I think it looks nice:

|Current|Proposal|
|--|--|
|![current](https://user-images.githubusercontent.com/333276/113489352-0434c480-94c4-11eb-8b5e-48974b84e18e.png) |![asciidoc-wg-hero](https://user-images.githubusercontent.com/333276/113489349-039c2e00-94c4-11eb-9d81-377510243953.png) |

References:
- https://edgenative.eclipse.org/
- https://openmobility.eclipse.org/
- https://jakarta.ee/
- https://ecdtools.eclipse.org/

What do you think?

**Comment by Mogztter** [comment]
Not sure if it's configurable, I will take a closer look.

**Comment by autumnfound** [comment]
> Not sure if it's configurable, I will take a closer look.

https://jakarta.ee/ also does this, and has all of its configs available on GitHub! What you're looking for is this line in the config.toml:

```
  header_wrapper_class = "header-default-bg-img"
```  

You'll want to add `featured-section-darken` as well, as that should help with font color. That should get you most of the way!

**Comment by Mogztter** [comment]
Ooops I saw your comment after I made some changes 😅 

Since we are already overriding `.header-wrapper`, I decided to move the background image from `featured-jumbotron ` to `header-wrapper` and, as you've mentioned, I also updated a few font colors.

I'm pretty happy with the result as it only requires a few changes 👍🏻
