### ISSUE TITLE
Add @Mogztter as committer to this repo

### ISSUE THREAD

**Issue by ahus1** [EclipseFdn/asciidoc-wg.eclipse.org#38]
As @Mogztter has shown commitment to improve this site in several ways I asked him to join this repo as a committer. I'm happy to write that he agreed! 

@eclipsewebmaster - could you please add permissions for @Mogztter to this repo? He should basically have the same permissions as Robert and me. 
Thanks!

(Quote of the day: "To infinity and beyond!" / Buzz Lightyear)

**Comment by chrisguindon** [comment]
@ahus1 You can ask me directly for access for website repos. 

You can ping webmaster if I am not responding.

**Comment by chrisguindon** [comment]
The invite is now pending!

**Comment by Mogztter** [comment]
Accepted! Thanks @chrisguindon  😉

**Comment by chrisguindon** [comment]
Welcome aboard @Mogztter! :)
