### ISSUE TITLE
Link to WG Website from WG Overview

### ISSUE THREAD

**Issue by ahus1** [EclipseFdn/asciidoc-wg.eclipse.org#43]
There is a list of all working groups here: https://www.eclipse.org/org/workinggroups/explore.php

All working groups with a homepage have a "Learn more" link, the AsciiDoc WG doesn't have that link yet. 

This issue is about changing this.

**Comment by mojavelinux** [comment]
Now that we've announced the website to the Steering Committee and the WG list, I think we're ready to make it official by enabling this link. Perhaps we need to notify EMO or member services about this so that they are aware of this request.

**Comment by mojavelinux** [comment]
This request has been submitted to EMO.

**Comment by mojavelinux** [comment]
cc: @SharonCorbett

**Comment by SharonCorbett** [comment]
Thanks Dan!  Yes, this request is in queue internally as well for the working group (request created by myself).  Our WebDev team had a new resource join today, so I suspect this issue will see some movement in the very very near future!  

Appreciate your patience...

**Comment by mojavelinux** [comment]
Perfect! Thanks for that info, Sharon!

**Comment by SharonCorbett** [comment]
This request is now resolved.  Thanks!

**Comment by mojavelinux** [comment]
I noticed that several of the working groups have a direct link to the members page from the working groups overview page. Could we get a similar link to https://asciidoc-wg.eclipse.org/membership/members/? Do we need a new issue for that request?

**Comment by SharonCorbett** [comment]
My bad...Let me take care of that as well!
