### ISSUE TITLE
Update link and tags in GitHub Repo

### ISSUE THREAD

**Issue by ahus1** [EclipseFdn/asciidoc-wg.eclipse.org#44]
The description of this GitHub repo still links to the Netlify site.

Current status (Screenshot):

![image](https://user-images.githubusercontent.com/3957921/114149784-918c7480-991b-11eb-93f4-376f521af6d9.png)

As the site is now live, this should change to https://asciidoc-wg.eclipse.org/

Also adding "AsciiDoc" as a tag would be nice.

**Comment by ahus1** [comment]
@chrisguindon - could you please change the link for this GitHub repo and add "AsciiDoc" as a tag? Thanks!

**Comment by mbarbero** [comment]
Done.
