### ISSUE TITLE
Updating banner image

### ISSUE THREAD

**Issue by shanda-eclipse** [EclipseFdn/asciidoc-wg.eclipse.org#57]
We noticed that the site is using the same banner image as eclipse.org, which may be confusing for some people. To help give AsciiDoc it's own look we have mocked up a couple of options for updated banner images. Let us know which (if either) you prefer and we can add the image files to the bug once you've provided your feedback.

Option A:
<img width="765" alt="AsciiDoc Banner A - People" src="https://user-images.githubusercontent.com/61751191/114756136-6e513300-9d28-11eb-891c-55b456883c37.PNG">

Option B:
<img width="766" alt="AsciiDoc Banner B - Abstract" src="https://user-images.githubusercontent.com/61751191/114756145-6f826000-9d28-11eb-8c06-29534a59b6b2.PNG">

**Comment by mojavelinux** [comment]
Until we have established an official brand / look for AsciiDoc, I prefer to go with something abstract. Therefore, I vote for Option B.

**Comment by ahus1** [comment]
+1 for abstract / option B

**Comment by shanda-eclipse** [comment]
Would you like us to prep the file for B, or are there other community members who would like to weigh in before moving forward?

**Comment by ahus1** [comment]
Please prep the file for B, don't wait for other community members, as there will be heading for an official brand in the medium term.

**Comment by meKokabi** [comment]
Here You Are!
![BannerASCCIDOC](https://user-images.githubusercontent.com/75500459/116238406-4b168280-a72f-11eb-99cc-b781c0f2cd99.jpg)

**Comment by ahus1** [comment]
Preview is available here: https://deploy-preview-62--eclipsefdn-asciidoc-wg.netlify.app/

Will merge it in 48h hours if no-one objects.

![image](https://user-images.githubusercontent.com/3957921/116288298-a8dbb680-a791-11eb-98fc-9e55f7620950.png)

**Comment by meKokabi** [comment]
Please consider left alignment for Title and button ( as shown on mockup
B). In addition to layout and composition considerations this makes it more
accessible.

**Comment by ahus1** [comment]
As I understood it, the placing of the text is standard with the Solstice theme we adopted. I see the same layout and placement of text on other sites like https://jakarta.ee/ and https://ecdtools.eclipse.org/

Could you please point me to a site that uses the Hugo/Solstice theme and has the layout you'd like to see, and point me to the settings/stylings I should apply?

I'd also be happy to change it to any other image that would allow us to keep the layout as standard as it is. 

Thanks!

**Comment by autumnfound** [comment]
Using the following as a starting point: 

In config.toml under `[Params]`
jumbotron_class = "col-xs-24 col-sm-18 col-md-14 col-lg-10 text-left"
jumbotron_tagline_class = "col-xs-24 text-left"

Large:
![image](https://user-images.githubusercontent.com/23018241/116294501-0b1ec200-a766-11eb-9447-740b200a2dac.png)

Medium:
![image](https://user-images.githubusercontent.com/23018241/116294578-212c8280-a766-11eb-801e-11f8dcadd4b2.png)

Small:
![image](https://user-images.githubusercontent.com/23018241/116294650-34d7e900-a766-11eb-9f9f-c9536be4d828.png)

**Comment by autumnfound** [comment]
> As I understood it, the placing of the text is standard with the Solstice theme we adopted. I see the same layout and placement of text on other sites like https://jakarta.ee/ and https://ecdtools.eclipse.org/
> 
> Could you please point me to a site that uses the Hugo/Solstice theme and has the layout you'd like to see, and point me to the settings/stylings I should apply?

Examples that have the left aligned text include https://iot.eclipse.org/ and https://jakartaone.org/. These sites are a little more a la carte, but it's a growing thematic choice that has yet to make its way to the full theme as an easy option (as this is a recent trend).

**Comment by meKokabi** [comment]
We made similar changes on the layout/ the left alignment  on the Business value page: https://www.eclipse.org/org/value/

same here, please have adequate margin-left for the texts align with  ASciDoc logo on top nav

**Comment by ahus1** [comment]
Hi @autumnfound - thank you for the CSS snippets and where to put them in the theme. 

Layouts displayed on the site match the images you provided.

I applied the changes. The updated preview is available here: https://deploy-preview-62--eclipsefdn-asciidoc-wg.netlify.app/

Will merge it in 48h hours if no-one objects.

**Comment by ahus1** [comment]
Hi @meKokabi - please have a look at the preview above. I'm more of a backend guy, so "adequate margin-left for the texts align with AsciiDoc logo on top nav" leaves me puzzled. Is the CSS change adequate enough?

**Comment by meKokabi** [comment]
Hello, it looks good now, and you've done it right.👍 Just you may want to consider making the heading a bit smaller, may be 10% smaller.

**Comment by mojavelinux** [comment]
I would prefer if "AsciiDoc Working Group" does not wrap. Could you either make the column wider or apply a nowrap rule to the text? Otherwise, looks good to me.

**Comment by ahus1** [comment]
I changed `col-lg-10` to `col-lg-11`, now the first layout (wide screen) has a little more space available. 

I'd like to avoid a no-wrap rule as this will affect all headlines on all pages AFAIK. 

![image](https://user-images.githubusercontent.com/3957921/116298708-0e817000-a79d-11eb-95c7-439fc9d8f763.png)

**Comment by mojavelinux** [comment]
Looks fantastic.

**Comment by meKokabi** [comment]
👍
