### ISSUE TITLE
Can't build successfully following the process in README file

### ISSUE THREAD

**Issue by linkfang** [EclipseFdn/asciidoc-wg.eclipse.org#72]
**Describe the bug**

I created [PR71](https://github.com/EclipseFdn/asciidoc-wg.eclipse.org/pull/71) to update the Registered Symbol to AsciiDoc and would like to preview my changes, but couldn't make it work.

With all 3 dependencies installed mentioned in README file - Node and NPM (14.7.1), Hugo, and Asciidoctor, when I run "hugo server --destination=public" command, I will get this error:
![image](https://user-images.githubusercontent.com/43075439/123290579-65769d80-d4df-11eb-90fa-cd6474865713.png)

After I change
```
_build:
  render: never
```
to
```
_build:
  render: false
```
The error above would gone, but then I will get this error:
![image](https://user-images.githubusercontent.com/43075439/123291198-e5046c80-d4df-11eb-9bdf-4e486d8cb70a.png)

I am using Windows 10 - WSL2 - Ubuntu.
Not sure if I missed something or did something wrong?

**Comment by ahus1** [comment]
Looking at the [deploy-preview of the other PR](https://deploy-preview-71--eclipsefdn-asciidoc-wg.netlify.app/) the (R) appeared nicely.

Could you please check the versions of hugo and Asciidoctor you're running in your local environment?

```
hugo version
asciidoctor --version
```

The site pinned Hugo to 0.76.5, still 0.81.0 works as well (as that is what I use locally). Depending on the version you might be using I need to update the README and/or update the version repos pins Hugo to. 

For Asciidoctor, any 2.x version should do. This site will download and install the latest version (2.0.15 at the moment).

**Comment by linkfang** [comment]
Thanks @ahus1 for providing the preview link, it does look good, as I need to update the logo with the R as well, so I will keep my PR as draft before I finish it.

For hugo, I think I can only get 0.69.3-1 on Ubuntu?
![image](https://user-images.githubusercontent.com/43075439/123468678-1bb1b400-d5c0-11eb-9daf-e398b4881821.png)

For Asciidoctor, it's 2.0.10.

Then, the issue might be the Hugo version?

**Comment by ahus1** [comment]
Seems so, I'm not using Ubuntu. You could choose to download the binary directly, see https://gohugo.io/getting-started/installing/#binary-cross-platform

You could try to run it using Docker. There's a Dockerfile in the project's root folder, but I'm afraid this isn't prepared to be used interactively live live reload. Still, it might be a starting point.

**Comment by linkfang** [comment]
Hi @ahus1 , 
After upgraded Hugo to 0.8.1, it works like a charm!

And the docker also works, but I find it's hard to reflect new changes. (Tried restarting the image and docker-compose up, both won't work) Anyways, I can always use `hugo server --destination=public`.

Thanks a lot for the help!
