### ISSUE TITLE
Website doesn't deploy to prod

### ISSUE THREAD

**Issue by ahus1** [EclipseFdn/asciidoc-wg.eclipse.org#73]
**Describe the bug**

After PR #70 the changes from the build are not visible on the production site yet (the meeting minutes of 2021-05-11 haven't been added to https://asciidoc-wg.eclipse.org/committees/).

@mbarbero - I see you committed some changes to the repo (see 1d76f84c27d72b49d5a8fe8e7ba6304e29c960d1), are you working on this issue already?

Thanks, 
Alexander

**Comment by mbarbero** [comment]
Yep, yesterday redeployment after the outage introduced some regression. I'm working on it.

**Comment by mbarbero** [comment]
Fixed. PR #70  has been deployed to production.

**Comment by ahus1** [comment]
Thanks for fixing this!
